### ISSUE TITLE
Lights break if they don't all have the same radius

### ISSUE THREAD

**Issue by haath** [defold/sample-lights-and-shadows#8] opened 2023-03-05 10:25 UTC
Hello,

I noticed that since your optimizations in [this commit](https://github.com/defold/sample-lights-and-shadows/commit/246e35b8e3eeb174255b764acd8935d1c0d60ac7) lights now break if there is at least one light in the scene with a different radius than the rest. In the example below the blue light radius was set to `300` while the red one was left at `256`. This from the current `master` branch with no other modifications.

![image](https://user-images.githubusercontent.com/29335643/222954186-3d389a05-e261-432d-bfa4-5a364786067a.png)

This issue was not present in the commit before that one. In fact even in [my PR](https://github.com/defold/sample-lights-and-shadows/pull/5), you can see in the gif that the radius is changing without issue. But what happened is that in your optimization commit you changed the default radius to `256`, and that is the exact same value that I was animating the blue radius to in my showcase! (see [this line](https://github.com/defold/sample-lights-and-shadows/blob/master/example/ball.script#L9)) So when you were working on it the radius stayed unchanged, and this is probably why you didn't notice the bug.

---

I am still a newbie at the rendering stuff, nonetheless I tried some things to identify the issue. Here is what I noticed:

- No matter how many lights you add, and with what sizes, the **last light in the list always gets drawn correctly**. All the rest are the ones that are drawn wrong.
- The above point made me think that maybe each light was messing up the other's `1xN` shadowmap, so I tried to separate them and created one shadowmap render target per light. This didn't fix the issue.
- For small differences in radius, it appears as if the light is offset both on the `x` and `y` axis by the same amount as the difference in radius. Not sure what is the significance of this.
- For larger differences in radius I can't notice any pattern, the lights are completely messed up.
- If a light is much larger than the other, it will either completely disappear, or stop casting shadows but stay intact at the correct position. (very confusing)
- It doesn't matter whether the lights overlap or not. Even if I place them on completely different parts of the scene, the issue still occurs the same way.

If you don't have the time to debug it yourself, feel free to share your guesses as to where the mistake might be, and I'll try my best to fix it!

**Comment by britzl** [comment] 2023-03-07 07:41
Ah, wow, you're right. It is indeed broken. The problem is the shared occluder and shadowmap render targets when the size of the lights aren't the same. If each light has its own render targets it works. You can test this here:

https://github.com/defold/sample-lights-and-shadows/archive/refs/heads/fix-light-size.zip

I need to spend some time debugging the drawcalls to better understand why the previous approach didn't work. A quick and easy way to do this is to use Spector.js (Chome/Firefox plugin) in the browser to step through the frame and see each step of the render process.

**Comment by haath** [comment] 2023-03-07 09:44
Ah darn, I went as far as to create a separate shadowmap target per light, but didn't think to also separate the occluder targets 😄 

Thanks for the quick reply, I will experiment a bit to see if this way can be optimized somehow.

**Comment by britzl** [comment] 2023-03-07 14:13
Cool. Let me know if the branch works as expected for you and then I'll merge it to master!

**Comment by haath** [comment] 2023-03-08 21:24
> Cool. Let me know if the branch works as expected for you and then I'll merge it to master!

It looks correct, thanks!

**Comment by britzl** [comment] 2023-03-08 22:02
Thanks @haath ! I've merged to master now.

**Closed as completed** 2023-03-08 22:02 UTC
